CREATE TABLE IF NOT EXISTS USER
(
    ID       BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN    VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    ROLE     VARCHAR(5)  NOT NULL
);

CREATE TABLE IF NOT EXISTS HOTEL
(
    ID       BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME     VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(50) NOT NULL,
    LUXURY   INT         NOT NULL
);

CREATE TABLE IF NOT EXISTS ROOM
(
    ID              BIGINT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HOTEL_ID        BIGINT     NOT NULL,
    NUM_OF_GUESTS   INTEGER    NOT NULL,
    PRICE_PER_NIGHT INTEGER    NOT NULL,
    CLASS           VARCHAR(8) NOT NULL,
    FOREIGN KEY (HOTEL_ID) references HOTEL (ID)
);

CREATE TABLE IF NOT EXISTS BOOKING
(
    ID         BIGINT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CLASS      VARCHAR(8) NOT NULL,
    START_DATE DATE       NOT NULL,
    END_DATE   DATE       NOT NULL,
);

CREATE TABLE IF NOT EXISTS BILL
(
    ID         BIGINT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT     NOT NULL,
    BOOKING_ID BIGINT     NOT NULL,
    STATUS     VARCHAR(7) NOT NULL,
    FOREIGN KEY (USER_ID) references USER (ID),
    FOREIGN KEY (BOOKING_ID) references BOOKING (ID)
);
