INSERT INTO USER (ROLE, LOGIN, PASSWORD)
VALUES ('ADMIN', 'Luther', '1234');
INSERT INTO USER (ROLE, LOGIN, PASSWORD)
VALUES ('USER', 'David', 'qwer');
INSERT INTO USER (ROLE, LOGIN, PASSWORD)
VALUES ('USER', 'Anton', 'qwer');

INSERT INTO HOTEL (NAME, LOCATION, LUXURY)
VALUES ('Dolphin', 'New York', 4);
INSERT INTO ROOM (HOTEL_ID, NUMBER, NUM_OF_GUESTS, PRICE_PER_NIGHT, CLASS)
VALUES (
        (SELECT ID FROM HOTEL WHERE NAME = 'Dolphin'),
        101,
        2,
        250,
        'LUX'
        );
INSERT INTO ROOM (HOTEL_ID, NUMBER, NUM_OF_GUESTS, PRICE_PER_NIGHT, CLASS)
VALUES (
        (SELECT ID FROM HOTEL WHERE NAME = 'Dolphin'),
        102,
        2,
        180,
        'STANDART'
        );
INSERT INTO ROOM (HOTEL_ID, NUMBER, NUM_OF_GUESTS, PRICE_PER_NIGHT, CLASS)
VALUES (
        (SELECT ID FROM HOTEL WHERE NAME = 'Dolphin'),
        201,
        2,
        120,
        'ECONOMY'
        );

INSERT INTO BOOKING (CLASS, START_DATE, END_DATE)
VALUES (
        'ECONOMY',
        '2019-03-01',
        '2019-03-07'
        );
INSERT INTO BOOKING (CLASS, START_DATE, END_DATE)
VALUES (
        'STANDART',
        '2019-04-01',
        '2019-04-07'
        );
INSERT INTO BOOKING (CLASS, START_DATE, END_DATE)
VALUES (
        'LUX',
        '2019-05-01',
        '2019-05-07'
        );

INSERT INTO BOOKING (CLASS, START_DATE, END_DATE)
VALUES (
        'STANDART',
        '2019-05-02',
        '2019-05-12'
        );
INSERT INTO BOOKING (CLASS, START_DATE, END_DATE)
VALUES (
        'ECONOMY',
        '2019-04-02',
        '2019-04-12'
        );

INSERT INTO BILL (ROOM_ID, USER_ID, BOOKING_ID, STATUS)
VALUES (
        (SELECT ID FROM ROOM WHERE NUMBER = 101),
        (SELECT ID FROM USER WHERE LOGIN = 'David'),
        (SELECT ID FROM BOOKING WHERE START_DATE = '2019-03-01'),
        'PAID'
        );
INSERT INTO BILL (ROOM_ID, USER_ID, BOOKING_ID, STATUS)
VALUES (
        (SELECT ID FROM ROOM WHERE NUMBER = 102),
        (SELECT ID FROM USER WHERE LOGIN = 'David'),
        (SELECT ID FROM BOOKING WHERE START_DATE = '2019-04-01'),
        'PAID'
        );
INSERT INTO BILL (ROOM_ID, USER_ID, BOOKING_ID, STATUS)
VALUES (
        (SELECT ID FROM ROOM WHERE NUMBER = 101),
        (SELECT ID FROM USER WHERE LOGIN = 'David'),
        (SELECT ID FROM BOOKING WHERE START_DATE = '2019-05-01'),
        'UNPAID'
        );

INSERT INTO BILL (ROOM_ID, USER_ID, BOOKING_ID, STATUS)
VALUES (
        (SELECT ID FROM ROOM WHERE NUMBER = 101),
        (SELECT ID FROM USER WHERE LOGIN = 'Anton'),
        (SELECT ID FROM BOOKING WHERE START_DATE = '2019-05-02'),
        'PAID'
        );
INSERT INTO BILL (ROOM_ID, USER_ID, BOOKING_ID, STATUS)
VALUES (
        (SELECT ID FROM ROOM WHERE NUMBER = 102),
        (SELECT ID FROM USER WHERE LOGIN = 'Anton'),
        (SELECT ID FROM BOOKING WHERE START_DATE = '2019-04-02'),
        'UNPAID'
        );